spring:
  datasource:
    hikari: 
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      jdbc-url: 
      username: 
      password:
     
---

logging:
  config: classpath:log4j2.yaml
  
 
  
  
